spring:
  profiles:
    include:
      - awsKey
cloud:
  aws:
    sqs:
      queue:
        url: https://sqs.us-east-2.amazonaws.com/266238301141/SQS-Study # aws SQS URL
    region:
      static: us-east-2
    credentials:
      instance-profile: true
    stack:
      auto: false